CREATE OR REPLACE PACKAGE Bowling IS
  TYPE Feld IS TABLE OF PLS_INTEGER;

  PROCEDURE Roll (Pins IN PLS_INTEGER);

  FUNCTION Score
    RETURN PLS_INTEGER;

  PROCEDURE Spiel (Reihe IN Bowling.Feld);
END Bowling;